---
# Common request parameters
TransactionId:
  type: string
  format: uuid

TransactionType:
  type: string
  enum:
    - ingress
    - egress

UtcTimestamp:
  type: integer
  format: int64
  description: A UNIX UTC timestamp in seconds.
  example: 1756773077
