---
# Common request parameters
TransactionId:
  type: string
  description: Transaction unique ID.
  example: f7bf189b-e7c2-4f85-bf73-0c45e7825a74

TransactionType:
  type: string
  enum:
    - ingress
    - egress

UtcTimestamp:
  type: integer
  format: int64
  description: A UNIX UTC timestamp in seconds.
  example: 1756773077
