---
openapi: 3.0.0
info:
  license:
    name: Unlicense
    url: https://unlicense.org/
  title: Echo API
  version: 1.0.0
  description: A simple API to echo a value back to the user.

servers:
  - url: /api

security:
  - bearerAuth: [] # Apply API key security globally to all operations


paths:
  /echo:
    $ref: "./paths/v1/Echo.yml"

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
      # Path to where the decode logic lives
      x-bearerInfoFunc: server.app.decode_token

#    get:
#      operationId: server.controllers.echo.do_echo
#      summary: Echo a value back
#      description: Returns the value provided in the query parameter, or an empty string if omitted.
#      parameters:
#        - name: value
#          in: query
#          required: false
#          description: The value to be echoed back.
#          schema:
#            type: string
